#lyrPts = QgsVectorLayer("D:/hse/GIS/project_qgis_repository/PyQGIS/Vector/scripts/nyc/NYC_MUSEUMS_GEO.shp", "Museums", "ogr")
lyr = QgsVectorLayer("D:/hse/GIS/project_qgis_repository/PyQGIS/Vector/scripts/nyc/NYC_MUSEUMS_GEO.shp", "Museums", "ogr")
QgsProject.instance().addMapLayers([lyr])
fts = lyr.getFeatures()
ft = fts.__next__()
lyr.selectByIds([ft.id()])
buff = ft.geometry().buffer(.2,8)
buffLyr =  QgsVectorLayer('Polygon?crs=epsg:4326', 'Buffer' , "memory")
pr = buffLyr.dataProvider()
b = QgsFeature()
b.setGeometry(buff)
pr.addFeatures([b])
buffLyr.updateExtents()
buffLyr.setLayerTransparency(70)
QgsMapLayerRegistry.instance().addMapLayers([buffLyr])