lyrPts = QgsVectorLayer("D:/hse/GIS/project_qgis_repository/PyQGIS/Vector/scripts/nyc/NYC_MUSEUMS_GEO.shp", "Museums", "ogr")
QgsProject.instance().addMapLayers([lyrPts])
selection = lyrPts.getFeatures(QgsFeatureRequest().setFilterExpression(u'"ZIP" = 10002'))
lyrPts.selectByIds([s.id() for s in selection])
iface.mapCanvas().zoomToSelected()